engines:
  eslint:
    enabled: true

ratings:
   paths:
   - "**.js"

exclude_paths:
  - "jasmine/"
  - "public/"
  - "src/"
  - "public/"
 - "public/js/inverted-index.js"
  - "!src/inverted-index.js"
  - "!src/utils.js"
