---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
  - "jasmine/lib/jasmine-2.3.4/jasmine.js"
  - "jasmine/"
  - "!jasmine/spec/inverted-index-test.js"
  - "public/"
  - "src/"
  - "public/"
  - "!src/inverted-index.js"
  - "!src/utils.js"
